site_name: FawltyDeps
site_description: "FawltyDeps: A Python Dependency Checker"
repo_url: https://github.com/tweag/fawltydeps
repo_name: tweag/FawltyDeps

theme: 
  name: material 
  favicon: material/check-circle
  icon:
    repo: fontawesome/brands/github
    logo: material/check-circle
  hjls_language:
    - python
    - yaml
    - json
  features:
    - search.suggest
  palette: 
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  
nav:

  - Home: index.md
  - Installation: installation.md
  - How it works:
    - Explanation: explanation.md
    - Design Document: DesignDoc.md
    - Code Design: CodeDesign.md
  - Reference: reference.md
  - How To Guides: how_to_guides.md
  - FAQ: FAQ.md
  - Contributing: CONTRIBUTING.md
  
markdown_extensions:
  - toc:
      permalink: true